name: Build and Deploy

# 手動Deploy
on: [ workflow_dispatch ]

# main pushで自動Deploy
# on:
#   push:
#     branches:
#       - main

# MicroCMS Webhook
# on:
#   repository_dispatch:
#     types: [update]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: npm ci
      run: npm ci

    - name: add env.production
      run: |
        touch .env.production
        echo "MICROCMS_API_KEY=${{ secrets.MICROCMS_API_KEY }}" >> .env.production
        echo "SERVICE_ID=${{ secrets.SERVICE_ID }}" >> .env.production

    - name: npm run build
      run: npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: s3 ls
      # run: aws s3 ls ${{ secrets.AWS_S3_BUCKET_NAME }}
      run: aws s3 sync --exact-timestamp public/aboutabout/ ${{ secrets.AWS_S3_BUCKET_NAME }}/test
      # run: aws s3 sync --exact-timestamp --delete public/about/index.html ${{ secrets.AWS_S3_BUCKET_NAME }}
    # - name: Invalidate CloudFront cache
    #   run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'
